Add a workaround for a issue in activesupport 3.2.16
Root cause is unclear, but the trace is:

    undefined method `hour' for 1:Fixnum
    /home/jzb/.gem/ruby/gems/activesupport-3.2.16/lib/active_support/time_with_zone.rb:344:in `rescue in get_period_and_ensure_valid_local_time'
    /home/jzb/.gem/ruby/gems/activesupport-3.2.16/lib/active_support/time_with_zone.rb:340:in `get_period_and_ensure_valid_local_time'
    /home/jzb/.gem/ruby/gems/activesupport-3.2.16/lib/active_support/time_with_zone.rb:47:in `initialize'
    /home/jzb/.gem/ruby/gems/activesupport-3.2.16/lib/active_support/values/time_zone.rb:287:in `new'
    /home/jzb/.gem/ruby/gems/activesupport-3.2.16/lib/active_support/values/time_zone.rb:287:in `parse'
    /home/jzb/src/community-middleman/lib/confcal.rb:20:in `block in tz_lookup'
    /home/jzb/src/community-middleman/lib/confcal.rb:19:in `each'
    /home/jzb/src/community-middleman/lib/confcal.rb:19:in `tz_lookup'

And work around come from
https://stackoverflow.com/questions/8329808/how-to-use-rails-date-helper-methods-outside-of-rails

Likely a change in some required gem somewhere in the dependency chain that masked the
error before.