Progressbar fail when run in cron, since there is no console
  ./fetch-dashboard.rb:45:in `<main>': undefined method `winsize' for nil:NilClass (NoMethodError)

So wrap all progress bar code with a test on IO.console to make sure we print anything
not needed.